version: '3.8'

services:
  animals-api:
    build: .
    container_name: meupet_animals_api
    restart: always
    ports:
      - "8083:8083"
    networks:
      - meupet-network
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/meupet
      # Aponta para o serviço de usuários usando o nome do container na rede Docker
      "QUARKUS_REST_CLIENT_COM_MEUPET_API_CLIENT_USUARIORESTCLIENT_URL": http://users-api:8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  meupet-network:
    external: true